-- 0021_market_snapshots_provenance.up.sql
-- Records WHERE each market snapshot came from, so simulator-era prices and
-- real vendor prices can never be read as the same thing.
--
-- Until now `source` lived only inside the stored JSON payload, which meant a
-- consumer had to fetch every object from S3 to tell a generated price from a
-- real one. Every consumer that reads prices -- Agent DNA, Autopsy, the
-- decision engine -- therefore had no cheap way to scope itself to one world.
-- With Season 1 (simulator) archived and Season 2 running on vendor data, that
-- is no longer a nicety: an agent's DNA averages its whole history, so without
-- this column it would blend two markets into one fingerprint and call it a
-- measurement.
--
-- ingest_mode is the structural half of the backfill/replay rule:
--   live     -- fetched as the most recent completed trading session, at the
--               time it was the most recent. Nobody knew the outcome.
--   backfill -- fetched for a historical date we already know the outcome of.
-- Both hold real prices and both are legitimate; only `live` may carry a
-- scored decision. agent-service refuses to open a competition tick on a
-- backfill snapshot, which is what stops a season being quietly replayed over
-- known history until it looks good -- see docs/market-data.md.
--
-- trading_date is the SESSION the snapshot describes, which is not the same as
-- tick_time (the job runs at 23:00 UTC, after the 21:00 UTC close). It is the
-- idempotency key for the daily fetch: the retries at 01:00 and 03:00 UTC ask
-- for the same session and must not create a second snapshot of it.
--
-- Existing rows are all simulator output -- the simulator was the only producer
-- that ever existed -- so the backfill below states that rather than leaving
-- 254 rows claiming 'unknown'.

ALTER TABLE market_snapshots
  ADD COLUMN source VARCHAR(30) NOT NULL DEFAULT 'unknown',
  ADD COLUMN ingest_mode VARCHAR(10) NOT NULL DEFAULT 'live',
  ADD COLUMN trading_date DATE,
  ADD COLUMN fetched_at TIMESTAMPTZ;

ALTER TABLE market_snapshots
  ADD CONSTRAINT market_snapshots_ingest_mode_check
  CHECK (ingest_mode IN ('live', 'backfill'));

-- Every snapshot that exists today was generated by the simulator.
UPDATE market_snapshots SET source = 'simulator' WHERE source = 'unknown';

-- PreviousRef scopes by source (a vendor snapshot's predecessor must be a
-- vendor snapshot, never a simulated one whose tick_time happens to interleave
-- with the backfilled range), so that lookup is the hot path.
CREATE INDEX idx_market_snapshots_source_tick
  ON market_snapshots(source, tick_time DESC);

-- One snapshot per session per source. The daily retries depend on this.
CREATE UNIQUE INDEX idx_market_snapshots_source_trading_date
  ON market_snapshots(source, trading_date)
  WHERE trading_date IS NOT NULL;
